from backend.dentist.models import *
from django.contrib.auth.hashers import make_password
import datetime


def init():
  k = Korisnik(email='anjajevtovic122@gmail.com', id=1, password= make_password('123'))
  k.save()
  k1 = Korisnik(email='nikolakrstic1@gmail.com', id=2, password = make_password('123') )
  k1.save()
  k2 = Korisnik(email='mihailojovanovic12@gmail.com', id=3, password = make_password('123'))
  k2.save()
  k3 = Korisnik(email='aleksavladic22@gmail.com', id=4, password = make_password('123'))
  k3.save()
  k4 = Korisnik(email='jovanjovanovic33@gmail.com', id=5, password = make_password('123'))
  k4.save()

  i = Informacije.create(k, 'Anja', 'Jevtovic', 1712000443322, 'Picture1.png', 'Pacijent')
  i.save()
  i1 = Informacije.create(k1, 'Nikola', 'Krstic', 1411000443322, 'Picture1.png', 'Pacijent')
  i1.save()
  i2 = Informacije.create(k2, 'Mihailo', 'Jovanovic', 1212000443322, 'Picture1.png', 'Pacijent')
  i2.save()
  i3 = Informacije.create(k3, 'Aleksa', 'Vladic', 1515000443322, 'Picture1.png', 'Stomatolog')
  i3.save()
  i4 = Informacije.create(k4, 'Jovan', 'Jovanovic', 1111000443322 , 'Picture1.png', 'Stomatolog')
  i4.save()

  o = Ocene.create(k, 1, 5,'Izuzetno prijatan ambijent sa prelepim morskim akvarijumom')
  o.save()
  o1 = Ocene.create(k1, 2, 5, 'izuzetno prijatani doktor i sestra učiniće da potpuno zaboravite da se nalazite u stomatološkoj stolici')
  o1.save()
  o2 = Ocene.create(k2, 3, 5, 'Od mene najviša ocena!!!')
  o2.save()
  o3 = Ocene.create(k3, 4, 4, 'Super anestezija, nisam nista osetila!')
  o3.save()
  o4 = Ocene.create(k4, 5, 5, ' Moja topla preporuka!')
  o4.save()

  u = Usluge.create(1, 5000, 'Sanacija obolelih potpornih tkiva zuba.')
  u.save()
  u1 = Usluge.create(2, 6000, 'Konzervativna (plombiranja) i protetska rekonstrukcija zuba.')
  u1.save()
  u2 = Usluge.create(3, 7000, 'Izbeljivanje zuba, keramičke fasete.')
  u2.save()
  u3 = Usluge.create(4, 8000, 'Sanacija obolelih zuba.')
  u3.save()

  iz = Izvestaj.create(1 , k, k4,'stomatolog-izvestaj', 'Karijes')
  iz.save()
  iz1 = Izvestaj.create(2, k1, k3, 'stomatolog-izvestaj', 'Parodontopatija')
  iz1.save()
  iz2 = Izvestaj.create(3, k2, k4, 'stomatolog-izvestaj', 'Drugi periapikalni procesi')
  iz2.save()
  iz3 = Izvestaj.create(4, k1, k4, 'stomatolog-izvestaj', 'Cista')
  iz3.save()
  iz4 = Izvestaj.create(5, k2, k3, 'stomatolog-izvestaj', 'Gingivitis')
  iz4.save()

  l = Lekovi.create(1, 'antibiotik pogodan za koštane infekcije, sinuzit itd.')
  l.save()
  l1 = Lekovi.create(2, 'lek koji se koristi u lečenju gljivičnih infekcija usta i drugih delova digestivnog trakta.')
  l1.save()
  l2 = Lekovi.create(3, 'lek koji se uzima za eliminaciju otoka.')
  l2.save()
  l3 = Lekovi.create(4, 'antibiotik, lek izbora kod lečenja parodontopatije,deluje na gram negativne bakterije.')
  l3.save()
  l4 = Lekovi.create(5, 'lek izbora kod mnogih dentogenih infekcija')
  l4.save()

  t = Terapija.create(iz, l, 20)
  t.save()
  t1 = Terapija.create(iz1, l1, 10)
  t1.save()
  t2 = Terapija.create(iz2, l2, 6)
  t2.save()
  t3 = Terapija.create(iz3, l2, 15)
  t3.save()
  t4 = Terapija.create(iz4, l3, 40)
  t4.save()


  p = Pitanja.create(1, k, 'Pitanje', 'Da li se anestezija naplacuje?' )
  p.save()
  p1 = Pitanja.create(2, k1, 'Pitanje', 'Koje je radno vreme ordinacije?')
  p1.save()
  p2 = Pitanja.create(3, k2, 'Pitanje', 'Nemam problema sa zubima ali mi se desni povlace. Kod koga da zakazem?')
  p2.save()
  p3 = Pitanja.create(4, k3, 'Pitanje', 'Kako se zakazuje pregled, da li je moguce online?')
  p3.save()

  pr = Pregledi.create(1, k, k4,"Endodoncija",datetime.datetime(2022, 5, 18, 15, 00), 60)
  pr.save()
  pr1 = Pregledi.create(2, k1, k3, "Rekonstruktivna stomatologija",datetime.datetime(2022, 5, 18, 16, 00), 100)
  pr1.save()
  pr2 = Pregledi.create(3, k2, k3, "Estetska stomatologija",datetime.datetime(2022, 5, 18, 18, 00), 80)
  pr2.save()

  z = Zahpre(idZ = 1, idK = k, idS = k3, opis = 'Uklanjanje kamenca',dvod = datetime.datetime(2022, 5, 18, 15, 00) , dvdo =datetime.datetime(2022, 5, 18, 16, 00))
  z.save()
  z1 = Zahpre(idZ = 2, idK = k1, idS = k3, opis = 'Rutinsko vadjenje zuba',dvod = datetime.datetime(2022, 5, 18, 15, 30), dvdo = datetime.datetime(2022, 5, 18, 16, 30))
  z1.save()
  z2 = Zahpre(idZ = 3, idK = k2, idS = k4, opis = 'Pregled za protezu',dvod = datetime.datetime(2022, 5, 18, 17, 00), dvdo = datetime.datetime(2022, 5, 18, 18, 00))
  z2.save()